---
apiVersion: v1
kind: ConfigMap
metadata:
  name: restore-job
data:
  island_backup_url: "s3://ark-backups/ark/backup/island/2021-07-08/arkmanager-island.2021-07-08_06.20.20.tar.bz2"
  island_restore_path: "/ark/island/ShooterGame/Saved/ArkTheIslandSave/"

  se_backup_url: ""
  se_restore_path: "/ark/scorchedearth/ShooterGame/Saved/ArkScorchedEarthSave/"

  abby_backup_url: ""
  abby_restore_path: "/ark/aberration/ShooterGame/Saved/ArkAberrationSave/"

  ext_backup_url: "s3://ark-backups/ark/backup/extinction/2021-07-08/arkmanager-ext.2021-07-08_06.20.13.tar.bz2"
  ext_restore_path: "/ark/extinction/ShooterGame/Saved/ArkExtinctionSave/"
  restore.sh: |
    #!/bin/sh
    yum install -y tree 
    echo "creating saved directories..."
    echo $island_restore_path
    echo $se_restore_path
    echo $abby_restore_path
    echo $ext_restore_path
    
    mkdir -p $island_restore_path
    mkdir -p $se_restore_path
    mkdir -p $abby_restore_path
    mkdir -p $ext_restore_path
    
    echo "configuring s3..."
    #backups if exists 
    if test -f "/s3cfg/.s3cfg"; then
      cp /s3cfg/.s3cfg /root/.s3cfg
      echo "s3cmd configured"
    else
      echo "s3cmd is not configured" 
    fi
    download(){    
      echo "downloading backups to restore..."
      mkdir -p /tmp/restore/$2/
      s3cmd get $1 /tmp/restore/$2.tar.bz2

      echo "extracting backup..."
      tar -xvjf /tmp/restore/$2.tar.bz2 -C /tmp/restore/$2/

      for f in /tmp/restore/$2/*/*; do
        cp -r "$f" $3
      done
    }
    if [ "$island_backup_url" == "" ]; then echo "";else download $island_backup_url "island" $island_restore_path;fi
    if [ "$se_backup_url" == "" ]; then echo "";else download $se_backup_url "se" $se_restore_path;fi
    if [ "$abby_backup_url" == "" ]; then echo "";else download $abby_backup_url "abby" $abby_restore_path;fi
    if [ "$ext_backup_url" == "" ]; then echo "";else download $ext_backup_url "ext" $ext_restore_path;fi
    
    echo "passing ark ownership to steam user"
    chown -R steam:steam /ark
---
apiVersion: batch/v1
kind: Job
metadata:
  name: restore
spec:
  template:
    spec:
      containers:
      - name: restore
        image: aimvector/ark-server-tools:0.2.0
        command: ['/bin/sh', '-c', '. /restore/restore.sh']
        env:
        - name: island_backup_url
          valueFrom:
            configMapKeyRef:
              name: restore-job
              key: island_backup_url
        - name: island_restore_path
          valueFrom:
            configMapKeyRef:
              name: restore-job
              key: island_restore_path
        - name: se_backup_url
          valueFrom:
            configMapKeyRef:
              name: restore-job
              key: se_backup_url
        - name: se_restore_path
          valueFrom:
            configMapKeyRef:
              name: restore-job
              key: se_restore_path
        - name: abby_backup_url
          valueFrom:
            configMapKeyRef:
              name: restore-job
              key: abby_backup_url
        - name: abby_restore_path
          valueFrom:
            configMapKeyRef:
              name: restore-job
              key: abby_restore_path
        - name: ext_backup_url
          valueFrom:
            configMapKeyRef:
              name: restore-job
              key: ext_backup_url
        - name: ext_restore_path
          valueFrom:
            configMapKeyRef:
              name: restore-job
              key: ext_restore_path
        volumeMounts:
        - name: restore
          mountPath: /restore
          readOnly: false
        - name: backup-secret
          mountPath: /s3cfg
          readOnly: false
        - name: ark
          mountPath: /ark
          readOnly: false
      restartPolicy: Never
      volumes:
      - name: backup-secret
        secret:
          secretName: ark-backup
      - name: restore
        configMap:
          name: restore-job
          defaultMode: 075
      - name: ark
        hostPath:
          path: /arkmanager
  backoffLimit: 4