ark:
  container_name: ark
  image: aimvector/ark-server-tools:0.0.1
  environment:
    - SERVERPASSWORD=""
    - ADMINPASSWORD=test
    - BACKUPONSTART=0
    - BACKUPONSTOP=0
    - WARNONSTOP=0
    - UPDATEONSTART=0
    - CLUSTER_ID=ThatDevOpsArkCluster
  volumes:
    - ark:/ark
  ports:
  - 30777:30777/udp 
  - 30778:30778/udp
  - 30015:30015/udp
  - 30016:30016/udp
  - 30779:30779/udp
  - 30780:30780/udp
  - 30017:30017/udp
  - 30018:30018/udp