---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ark-configuration
data:
  update-configs.sh: |
    #!/bin/sh
    cd /conf 
    cp GameUserSettings.ini /ark/server/ShooterGame/Saved/Config/LinuxServer/
    cp Game.ini /ark/server/ShooterGame/Saved/Config/LinuxServer/
    cp arkmanager.cfg /ark/
    
  
  GameUserSettings.ini: |+
    [ServerSettings]
    alwaysNotifyPlayerJoined=True
    alwaysNotifyPlayerLeft=True
    DayTimeSpeedScale=0.50000
    TamingSpeedMultiplier=5.00000
    HarvestAmountMultiplier=4
    DifficultyOffset=4
    XPMultiplier=4.00000
    EnablePVPGamma=0
    EnablePVEGamma=0
    AdminLogging=false
    PerPlatformMaxStructuresMultiplier=10.00000
    ForceFlyerExplosives=0
    MaxPlatformSaddleStructureLimit=100
    AllowCrateSpawnsOnTopOfStructures=1
    AllowFlyingStaminaRecovery=True
    ShowMapPlayerLocation=True
    allowThirdPersonPlayer=True
    ServerCrosshair=True
    ServerPassword=
    ServerAdminPassword=
    RCONEnabled=True
    RCONPort=32330
    TheMaxStructuresInRange=10500.000000
    OxygenSwimSpeedStatMultiplier=1.000000
    StructurePreventResourceRadiusMultiplier=1.000000
    TribeNameChangeCooldown=15.000000
    PlatformSaddleBuildAreaBoundsMultiplier=1.000000
    StructurePickupTimeAfterPlacement=30.000000
    StructurePickupHoldDuration=0.500000
    AllowIntegratedSPlusStructures=True
    AllowHideDamageSourceFromLogs=True
    RaidDinoCharacterFoodDrainMultiplier=1.000000
    PvEDinoDecayPeriodMultiplier=1.000000
    KickIdlePlayersPeriod=3600.000000
    AutoSavePeriodMinutes=15.000000
    ListenServerTetherDistanceMultiplier=1.000000
    MaxTamedDinos=5000.000000
    ItemStackSizeMultiplier=1.000000
    RCONServerGameLogBuffer=600.000000
    AllowHitMarkers=True
    [/Script/ShooterGame.ShooterGameUserSettings]
    MasterAudioVolume=1.000000
    MusicAudioVolume=1.000000
    SFXAudioVolume=1.000000
    VoiceAudioVolume=1.000000
    UIScaling=1.000000
    UIQuickbarScaling=0.650000
    CameraShakeScale=0.650000
    bFirstPersonRiding=False
    bThirdPersonPlayer=False
    bShowStatusNotificationMessages=True
    TrueSkyQuality=0.000000
    FOVMultiplier=1.000000
    GroundClutterDensity=0.000000
    bFilmGrain=False
    bMotionBlur=False
    bUseDistanceFieldAmbientOcclusion=False
    bUseSSAO=False
    bShowChatBox=True
    bCameraViewBob=True
    bInvertLookY=False
    bFloatingNames=True
    bChatBubbles=True
    bHideServerInfo=False
    bJoinNotifications=False
    bCraftablesShowAllItems=False
    bLocalInventoryItemsShowAllItems=False
    bLocalInventoryCraftingShowAllItems=True
    bRemoteInventoryItemsShowAllItems=False
    bRemoteInventoryCraftingShowAllItems=False
    bRemoteInventoryShowEngrams=True
    LookLeftRightSensitivity=1.000000
    LookUpDownSensitivity=1.000000
    GraphicsQuality=1
    ActiveLingeringWorldTiles=1
    ClientNetQuality=3
    LastServerSearchType=0
    LastServerSort=2
    LastPVESearchType=-1
    LastDLCTypeSearchType=-1
    LastServerSortAsc=True
    LastAutoFavorite=True
    LastServerSearchHideFull=False
    LastServerSearchProtected=False
    LastServerSearchIncludeServersWithActiveMods=True
    HideItemTextOverlay=True
    bQuickToggleItemNames=True
    bDistanceFieldShadowing=False
    LODScalar=0.780000
    bToggleToTalk=False
    HighQualityMaterials=True
    HighQualitySurfaces=True
    bTemperatureF=False
    bDisableTorporEffect=False
    bChatShowSteamName=False
    bChatShowTribeName=True
    bReverseTribeLogOrder=False
    EmoteKeyBind1=0
    EmoteKeyBind2=0
    bNoBloodEffects=False
    bLowQualityVFX=False
    bSpectatorManualFloatingNames=False
    bSuppressAdminIcon=True
    bUseSimpleDistanceMovement=False
    bDisableMeleeCameraSwingAnims=False
    bHighQualityAnisotropicFiltering=False
    bUseLowQualityLevelStreaming=True
    bPreventInventoryOpeningSounds=False
    bPreventItemCraftingSounds=False
    bPreventHitMarkers=False
    bPreventCrosshair=False
    bPreventColorizedItemNames=False
    bHighQualityLODs=False
    bExtraLevelStreamingDistance=False
    bEnableColorGrading=True
    DOFSettingInterpTime=0.000000
    bDisableBloom=False
    bDisableLightShafts=False
    LastJoinedSessionPerCategory=" "
    LastJoinedSessionPerCategory=" "
    LastJoinedSessionPerCategory=" "
    LastJoinedSessionPerCategory=" "
    LastJoinedSessionPerCategory=" "
    LastJoinedSessionPerCategory=" "
    LastJoinedSessionPerCategory=" "
    LastJoinedSessionPerCategory=" "
    LastJoinedSessionPerCategory=" "
    bDisableMenuTransitions=False
    bEnableInventoryItemTooltips=True
    bRemoteInventoryShowCraftables=False
    bNoTooltipDelay=False
    LocalItemSortType=0
    LocalCraftingSortType=0
    RemoteItemSortType=0
    RemoteCraftingSortType=0
    VersionMetaTag=1
    ShowExplorerNoteSubtitles=False
    DisableMenuMusic=False
    DisableDefaultCharacterItems=False
    bHideFloatingPlayerNames=False
    bHideGamepadItemSelectionModifier=False
    bToggleExtendedHUDInfo=False
    PlayActionWheelClickSound=True
    CompanionReactionVerbosity=3
    EnableEnvironmentalReactions=True
    EnableRespawnReactions=True
    EnableDeathReactions=True
    EnableSayHelloReactions=True
    EnableEmoteReactions=True
    EnableMovementSounds=True
    CompanionSubtitleVerbosityLevel=3
    CompanionIsHiddenState=False
    MaxAscensionLevel=0
    bHostSessionHasBeenOpened=False
    bForceTPVCameraOffset=False
    bDisableTPVCameraInterpolation=False
    bFPVClimbingGear=False
    bFPVGlidingGear=False
    Gamma1=2.200000
    Gamma2=3.000000
    AmbientSoundVolume=1.000000
    bAllowAnimationStaggering=True
    bUseOldThirdPersonCameraTrace=False
    bUseOldThirdPersonCameraOffset=False
    bLowQualityAnimations=True
    bShowedGenesisDLCBackground=False
    bViewedAnimatedSeriesTrailer=False
    bViewedARK2Trailer=False
    bUseVSync=False
    MacroCtrl0=
    MacroCtrl1=
    MacroCtrl2=
    MacroCtrl3=
    MacroCtrl4=
    MacroCtrl5=
    MacroCtrl6=
    MacroCtrl7=
    MacroCtrl8=
    MacroCtrl9=
    ResolutionSizeX=1280
    ResolutionSizeY=720
    LastUserConfirmedResolutionSizeX=1280
    LastUserConfirmedResolutionSizeY=720
    WindowPosX=-1
    WindowPosY=-1
    bUseDesktopResolutionForFullscreen=False
    FullscreenMode=2
    LastConfirmedFullscreenMode=2
    Version=5
    [ScalabilityGroups]
    sg.ResolutionQuality=100
    sg.ViewDistanceQuality=3
    sg.AntiAliasingQuality=3
    sg.ShadowQuality=3
    sg.PostProcessQuality=3
    sg.TextureQuality=3
    sg.EffectsQuality=3
    sg.TrueSkyQuality=3
    sg.GroundClutterQuality=3
    sg.IBLQuality=1
    sg.HeightFieldShadowQuality=3
    sg.GroundClutterRadius=10000
    [SessionSettings]
    SessionName=mytestserver
    [/Script/Engine.GameSession]
    MaxPlayers=70

  arkmanager.cfg: |+
    # --- USER CONFIG --- #
    # ARK server options - use ark_<optionname>=<value>
    # comment out these values if you want to define them
    # inside your GameUserSettings.ini file
    serverMap=${SERVERMAP}                                          # server map (default TheIsland)
    #serverMapModId="469987622"                                     # Uncomment this to specify the Map Mod Id (<fileid> in http://steamcommunity.com/sharedfiles/filedetails/?id=<fileid>)
    #ark_TotalConversionMod="496735411"                             # Uncomment this to specify a total-conversion mod
    ark_SessionName=${SESSIONNAME}                                  # if your session name needs special characters please use the .ini instead
    ark_ServerPassword=${SERVERPASSWORD}                            # ARK server password, empty: no password required to login
    ark_ServerAdminPassword=${ADMINPASSWORD}                        # ARK server admin password, KEEP IT SAFE!
    ark_MaxPlayers=${MAX_PLAYERS}                                   # Number MAX of player
    # ark_bRawSockets=""                                            # Uncomment if you want to use ark raw socket (instead of steam p2p) [Not recommended]
    arkflag_log=""


    # ----- Mods ----- #
    #ark_GameModIds="487516323,487516324,487516325"                     # Uncomment to specify additional mods by Mod Id separated by commas
    # Mod OS Selection
    mod_branch=Windows
    # Add mod-specific OS selection below:
    #mod_branch_496735411=Windows
    # ----------------#

    # ARK server flags - use arkflag_<optionname>=true
    #arkflag_OnlyAdminRejoinAsSpectator=true                            # Uncomment to only allow admins to rejoin as spectator
    #arkflag_DisableDeathSpectator=true                                 # Uncomment to disable players from becoming spectators when they die

    # ARK server options - i.e. for -optname=val, use arkopt_optname=val
    #arkopt_StructureDestructionTag=DestroySwampSnowStructures

    #ark_AltSaveDirectoryName="SotF"                                    # Uncomment to specify a different save directory name

    # Update warning messages
    # Modify as desired, putting the %d replacement operator where the number belongs
    msgWarnUpdateMinutes="This ARK server will shutdown for an update in %d minutes"
    msgWarnUpdateSeconds="This ARK server will shutdown for an update in %d seconds"
    msgWarnRestartMinutes="This ARK server will shutdown for a restart in %d minutes"
    msgWarnRestartSeconds="This ARK server will shutdown for a restart in %d seconds"
    msgWarnShutdownMinutes="This ARK server will shutdown in %d minutes"
    msgWarnShutdownSeconds="This ARK server will shutdown in %d seconds"

    # config environment
    arkwarnminutes="60"                                                 # number of minutes to warn players when using update --warn
    arkBackupPreUpdate="false"                                          # set this to true if you want to perform a backup before updating

    # Options to automatically remove old backups to keep backup size in check
    # Each compressed backup is generally about 1-2MB in size.
    arkMaxBackupSizeMB="500"                                            # Set to automatically remove old backups when size exceeds this limit
    #arkMaxBackupSizeGB="2"                                             # Uncomment this and comment the above to specify the limit in whole GB

  Game.ini: |+
    [/script/shootergame.shootergamemode]
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
    OverridePlayerLevelEngramPoints=100
---