apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ark-server
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: linode-block-storage-retain